name: 'waveworks_dbt_tutorial'
version: '1.0'
config-version: 2

profile: 'waveworks_profile'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
